### PR TITLE
fix: Invalid 'end_col': out of range

### PR DESCRIPTION
**Pull request by ueaner**
`Invalid 'end_col': out of range` will be triggered when the last line of the code to be executed contains `<TAB>`, such as not using a specific number of spaces instead of `<TAB>`: `expandtab=true tabstop=4 `.

### CODE REVIEW

**Comment by ueaner** [comment]
I am using neovim version 0.9.1. Test works fine in python, php, go languages.

Test steps:
1. Lines 2 and 3 start with `<TAB>`
2. Select line 2 (variable definition) and line 3 (print variable value)
3. Execute visual_send


for python (ipython):
```python
def tt():
	str = "\t钢铁侠abć very looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog"
	print(str)
```

for php (php -a):
```php
function tt() {
	$str = "\t钢铁侠abć very looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog";
	echo $str;
}
```

for go ([yaegi](https://github.com/traefik/yaegi)):
```go
func main() {
	str := "\t钢铁侠abć very looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog"
	fmt.Println(str)
}
```

**Comment by hkupty** [comment]
Nice! Sorry for not replying earlier.. I'm out on vacations so it is a bit tough for me to keep an eye at the PRs. 

This seems to partially revert #221. I guess the important part is `strcharpart`  rather than `strdisplaywidth`.
To avoid going back-and-forth with this PR, can you test with a short string, just like the original issue?

I can probably test once I'm back but I assume you'll want to get this merged earlier than that.

**Comment by ueaner** [comment]
@hkupty It's OK. Wishes you to have a happy vacation!

Thanks for the info mentioned in the reply, I'll take the time to look at the original issue and test it.

**Comment by ueaner** [comment]
Hi @hkupty, I tested `a = "abć"` with `send_line`, `visual_send` and `send_motion` and it works fine in python(ipython), php (php -a), go ([yaegi](https://github.com/traefik/yaegi)). So there should be no impact on issue #217.

**Comment by hkupty** [comment]
Nice, thanks for taking the time to test it out. I'm confident that it was `strcharpart` that solved that issue then, so I'll merge your PR and hopefully solve the issues around this for once and for all :)

Thank you very much for your effort in this PR and in helping making iron better :D

**Pull request merged**
