### PR TITLE
Python REPL improvements

### LINKED ISSUE #146: Missing linefeed --> Visualmode
When using visual_send() all lines are concatenated without a linefeed, which leeds to syntax/indent errors in python.

Setup: NVim on Windows, Python 3.x 
Since I am completely new to Vimscript and Lua I might have overseen something, but changing 
`table.insert(tbl, i)` into `table.insert(tbl, i .. "\13")` in tables.lua --> fns.extend fixed this issue for me.

Btw. thanks for this plugin!

### PR DESCRIPTION
**Pull request by Mike325**
- Fix #146 
- Prefer `python3` over `python`

### CODE REVIEW

**Comment by yelled1** [comment]
May be a little too early to close:
When I did lines 1~6 it was fine, but ...
9~28 I get errors.
``` 1 import sys
  2 import pyodbc
  3 from dotenv import load_dotenv, find_dotenv
  4 from hlper_fun_db import get_db_env
  5 # Set environment path and load db credentials from path
  6 load_dotenv(dotenv_path=find_dotenv(), verbose=True)
  7
  8
  9 def connect_database(env, trusted=True, native=False, debug=False):
 10     """ Connects to Ms Sql Server """
 11     if sys.platform == 'linux':
 12         driver = "ODBC Driver 17 for SQL Server"
 13     elif native:
 14         driver = "SQL Server Native Client 11.0"
 15     else:
 16         driver = 'ODBC Driver 17 for SQL Server'
 18
 19     trust = 'yes' if trusted else 'no'
 20
 21     conn_str = "Driver={%s};Server=%s;Database=%s;User=%s;PWD=%s;Port=%s;" + \
 22                "Trusted_Connection=%s;encoding='latin1',fast_executemany=True"
 23     database, user, pwd, server, port = get_db_env(env, debug)
 24
 25     if debug:
 26         print('debug connetion string is:')
 27         print(conn_str %(driver, server, database, user, 'FAKE_PWD', port, trust))
 28     return pyodbc.connect(conn_str %(driver, server, database, user, pwd, port, trust))
```
Close but not quite do the job unless you do not wish to write any functions
```
dentationError: unexpected indent
 58 >>>     return pyodbc.connect(conn_str %(driver, server, database, user, pwd, port, trust))
 59   File "<stdin>", line 1
 60     return pyodbc.connect(conn_str %(driver, server, database, user, pwd, port, trust))
 61     ^
 62 IndentationError: unexpected indent
```
Great effort though!

**Comment by Mike325** [comment]
I did notice this issue, but I thought this should be a PR on its own :)

**Comment by yelled1** [comment]
Of course, you r absolutely right. Need to step & know what was fixed 1 at a time.

**Comment by hkupty** [comment]
Should I revert this PR and wait for the full fix?

**Comment by yelled1** [comment]
No.... revert, pls. As this may not be perfect, this is still a welcome improvement. Working in Windows nowadays. So, this really helps.

**Pull request merged**
