### PR TITLE
Remove sensitive data from commit 08153d4

### PR DESCRIPTION
**Pull request by yelircaasi**
Resolves https://github.com/Vigemus/iron.nvim/issues/331.

Changed commit message of [08153d4](https://github.com/Vigemus/iron.nvim/commit/08153d460db933a8ab118858de05be166805824b).

### CODE REVIEW

**Comment by hkupty** [comment]
@mschilli87 I'm sorry this caused distress and frustration. I'm in no position to judge the severity or impact that "a (one-time, single-line change) contributor not understanding git and/or their company policy" has on this contributor's life.

Having that said, it didn't seem severely alarming in my head as I've seen previous projects doing history rewrites in the past.

Still, I sympathize with your situation and I'll take this in consideration when/if similar measures are needed in the future.

**Comment by mschilli87** [comment]
@hkupty: Thanks for the feedback. I have no strong objections against this particular case and I agree that on the personal level this could mean a great deal. I doubt that this will remove all traces of that commit though tbh but I think it speaks for you that you take on this chore to help a 'random' (minor) contributor. I did not mean to belittle anyone I just found this very unusual and felt like sharing my concerns.

**Comment by hkupty** [comment]
Thank you for your kind words and once again sorry for the inconvenience. :)

**Comment by hkupty** [comment]
I'll close the pr as the fix is in place already. Thanks a lot for taking the lead, @yelircaasi

**Pull request closed without merging**
